apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - configMap_prestashop.yaml
  - deployment_mariadb.yaml
  - deployment_prestashop.yaml
  - namespace_223000-kube.yaml
  - pv_pvc.yaml
  - secret_prestashop.yaml
  - service_mariadb.yaml
  - service_prestashop.yaml